#!/bin/bash

# select の中身はループになってるのでbreakで終わらせてあげる
select color in red blue green yellow; do
  case "$color" in
    red)
      echo "stop"
      ;;
    blue|green)
      echo "go"
      ;;
    yellow)
      echo "caution"
      ;;
    *)
      echo "wrong signal"
      break
  esac
done
